version: "3.8"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"  # Build-time argument to differentiate dev and prod
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - ./app:/app  # Mount the local app directory to the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"  # Start the Django dev server
    environment:
      DEBUG: "true"  # Enable debugging mode for Django
      ALLOWED_HOSTS: "0.0.0.0,localhost"  # Add multiple allowed hosts
    depends_on:
      - db  # Ensure the database container starts first

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: "your_user"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "your_database"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
