# ---
# name: Checks

# on: [push]

# jobs: 
#   test-lint: 
#     name: Test and Lint
#     runs-on: ubuntu-20.04 
#     steps: 
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with: 
#           username: ${{secrets.DOCKERHUB_USER}}
#           password: ${{secrets.DOCKERHUB_TOKEN}}
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Test
#         run: docker compose run --rm app sh -c "python manage.py test"
#       - name: Lint
#         run: docker compose run --rm app sh -c "flake8"


name: CI for Recipe App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose Plugin
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      # Step 3: Build Docker Services
      - name: Build Docker Services
        run: docker compose build

      # Step 4: Run Linting with flake8
      - name: Run Linting
        run: docker compose run --rm app sh -c "flake8 ."

      # Step 5: Run Tests
      - name: Run Tests
        run: docker compose exec app pytest
