# ---
# name: Checks

# on: [push]

# jobs: 
#   test-lint: 
#   name: Test and Lint
#   runs-on: ubuntu-20.04 
#   steps: 
#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with: 
#         username: ${{secrets.DOCKERHUB_USER}}
#         password: ${{secrets.DOCKERHUB_TOKEN}}
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Test
#       run: docker compose run --rm app sh -c "python manage.py test"
#     - name: Lint
#       run: docker compose run --rm app sh -c "flake8"

# name: Checks

# on: 
#   push:
#     branches:
#       - main  # Run only on the main branch
#   pull_request:  # Run on pull requests as well

# jobs: 
#   test-lint: 
#     name: Test and Lint
#     runs-on: ubuntu-20.04
#     steps: 
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with: 
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Test Application
#         run: docker-compose run --rm app sh -c "python manage.py test"
      
#       - name: Lint Code
#         run: docker-compose run --rm app sh -c "flake8"
name: Checks

on: 
  push:
    branches:
      - main  # Run only on the main branch
  pull_request:  # Run on pull requests as well

jobs: 
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker Containers
        run: docker-compose build

      - name: Test Application
        run: docker-compose run --rm app sh -c "python manage.py test"
      
      - name: Lint Code
        run: docker-compose run --rm app sh -c "flake8"
