name: CI/CD Workflow for Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose Plugin
      - name: Install Docker Compose Plugin
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      # Step 4: Build Docker Services
      - name: Build Docker Services
        run: docker compose build

      # Step 5: Start Docker Services
      - name: Start Docker Services
        run: docker compose up -d

      # Step 6: Run Tests (if applicable)
      - name: Run Tests
        run: |
          docker compose exec <service-name> pytest
