name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # Updated version
      - name: Checkout Code
        uses: actions/checkout@v3 # Updated version

    
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Containers
        run: docker compose build

      - name: Test Application
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Lint Code
        run: docker-compose run --rm app sh -c "flake8"
